# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'antonioR' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Generate env.xcconfig from .env via react-native-config
    root = Pod::Config.instance.installation_root.parent
    xcconfig_path = root.join('ios', 'env.xcconfig')
    system("ruby", root.join('node_modules', 'react-native-config', 'ios', 'ReactNativeConfig', 'BuildXCConfig.rb').to_s, root.to_s, xcconfig_path.to_s)

    # Include env.xcconfig in Pods target support xcconfigs (used by app target)
    pods_dir = Pod::Config.instance.installation_root.join('Pods')
    ['debug', 'release'].each do |mode|
      xcconfig_file = pods_dir.join('Target Support Files', 'Pods-antonioR', "Pods-antonioR.#{mode}.xcconfig")
      next unless xcconfig_file.exist?
      contents = xcconfig_file.read
      include_line = "#include \"#{xcconfig_path}\""
      unless contents.include?(include_line)
        File.open(xcconfig_file, 'a') { |f| f.puts("\n#{include_line}") }
      end
    end
  end
end
